name: "PR checks - Push"

on:
  pull_request_target:
    branches:
      - main

jobs:
  push-images:
    runs-on: ubuntu-20.04

    steps:
      - name: Wait for build
        uses: lewagon/wait-on-check-action@v0.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          check-name: build-images
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 5
      
      - name: Extract artifacts
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: "PR checks - Build"

      - name: Push
        run: |
          echo "Pushing"
          sleep 15s
          echo "done"
